

LAUNCH_DIR=$PWD


## mogenerator wants this
cd ~
   HOME_DIR=$PWD
cd "$LAUNCH_DIR"


cd ../..
   PROJECT_ROOT=$PWD
cd "$LAUNCH_DIR"

MODEL_DIR=$PROJECT_ROOT/lib/RIApi/RIApi.xcdatamodeld/RIApi.xcdatamodel
OUTPUT_DIR=$PROJECT_ROOT/lib/RIApi/RIApi/CoreDataAutoGenerated

echo "LAUNCH_DIR - $LAUNCH_DIR"
echo "HOME_DIR   - $HOME_DIR"
echo "MODEL_DIR  - $MODEL_DIR"
echo "OUTPUT_DIR - $OUTPUT_DIR"

mkdir -p "$OUTPUT_DIR"

echo /bin/bash "$PWD/CoreData-GenerateModel.sh" "$MODEL_DIR" "$OUTPUT_DIR"
/bin/bash "$PWD/CoreData-GenerateModel.sh" "$MODEL_DIR" "$OUTPUT_DIR"


## fix headers style

HUMAN_DIR=$OUTPUT_DIR/Human
MACHINE_DIR=$OUTPUT_DIR/Machine

cd "$HUMAN_DIR"
   HEADERS=$( ls -1 *.h )

   for HEADER in $HEADERS; do
      sed -i .sed 's/\#import "/\#import <RIApi\/CoreDataAutoGenerated\/Machine\//g' $HEADER
      sed -i .sed 's/.h"/.h>/g' $HEADER
   done
cd "$LAUNCH_DIR"

cd "$MACHINE_DIR"
   HEADERS=$( ls -1 *.h )

   for HEADER in $HEADERS; do
      sed -i .sed 's/\#import "/\#import <RIApi\/CoreDataAutoGenerated\/Human\//g' $HEADER
      sed -i .sed 's/.h"/.h>/g' $HEADER
   done
cd "$LAUNCH_DIR"

